version: "3.8"

services:

  api:
    build:
      context: ./backend
    container_name: incident-backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: jurassic
      DB_PORT: 3306
      API_TOKEN: JurassicSecretToken
    depends_on:
      - db
    networks:
      - backend-net

  frontend:
    build:
      context: ./frontend
    container_name: incident-frontend
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - backend-net

  db:
    image: mysql:8
    container_name: incident-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jurassic
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: jurassic-phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge

volumes:
  mysql_data:

