services:
  frontend:
    build:
      context: ./frontend
    container_name: incident-frontend
    ports:
      - "8080:80"
    depends_on:
      - api

  api:
    build:
      context: .
    container_name: jurassic-backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: jurassic
      DB_PORT: 3306
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: jurassic-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jurassic
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: jurassic-phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  mysql_data:
