services:
  frontend:
    build:
      context: ./frontend
    container_name: incident-frontend
    ports:
      - "8080:80"
    depends_on:
      - api

  db:
    image: mysql:8
    container_name: jurassic-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jurassic
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:                # ← AJOUTE CETTE SECTION
      test: ["CMD", "mysqladmin", "ping", "-p$password", "-h", "localhost"]
      interval: 5s              # teste toutes les 5 s
      retries: 10               # après 10 échecs, l’état devient unhealthy
      start_period: 10s         # laisse 10 s de marge au démarrage

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: jurassic-phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8081:80"
    depends_on:
      - db

  api:
    build: .
    container_name: jurassic-backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db          # <-- ici !
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: jurassic
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data:
