apiVersion: apps/v1
kind: Deployment
metadata:
  name: incident-mysql
  labels:
    app: incident-mysql
spec:
  selector:
    matchLabels:
      app: incident-mysql
  template:
    metadata:
      labels:
        app: incident-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: incident-mysql-secret
                  key: password
            - name: MYSQL_DATABASE
              value: jurassic
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: incident-mysql-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: incident-mysql-secret
                  key: password
          volumeMounts:
            - name: mysql-pv
              mountPath: /var/lib/mysql
          ports:
            - containerPort: 3306
      volumes:
        - name: mysql-pv
          persistentVolumeClaim:
            claimName: incident-mysql-pvc